jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds 

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.y.twitter_clone.controller
  paths-to-match: /api/**

springdoc.api-docs.info:
  title: Twitter Clone API
  description: Twitter Clone Backend API Documentation
  version: 1.0.0
  contact:
    name: Twitter Clone Team
    email: support@twitterclone.com 